### ISSUE TITLE
Проставить генам criterion (причины/критерии отбора)

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#103]
Для всех генов в датасете, которые добавлены в базу, нужно:

1. проверить заполнены ли у них эксперименты в age_related_change (если criterion в датасете —  Age-related changes in gene expression/protein activity in humans) 
3. проверить заполнены ли у них эксперименты в gene_to_longevity_effect (если criterion в датасете — Association of genetic variants and gene expression levels with longevity). 

Для всех генов из датасета, которые добавлены в базу, нужно проставить причину отбора из колонки `criterion` в датасете. Таблица в БД называется `comment_cause`. Если такой критерий как в датасете уже присвоен гену, то ничего не менять. 

Если критерии у гена есть, в таблице `gene` у гена проставить `0` в колонке `isHidden` 

При выполнении скрипта, составить список генов, которые есть в датасете, но отсутстсвуют в базе. Сохранить это в виде лога в папке с приложением на сервере. Лучше прикрепить его потом к этой задаче.
[criteria.tsv.zip](https://github.com/open-genes/open-genes-cms/files/9247069/criteria.tsv.zip)

**Comment by bavdalimbaev** [comment]
будет папка **storage/datalogs/***
здесь будут хранится логи по типу таких задач, название примерно такой **date_time_genesNotExist.csv**

дальнейшем нужно будет загружать датасеты в таких названиях что бы хранить историю, **20220805_criteria.csv**

**Comment by bavdalimbaev** [comment]
команда для запуска:
**php ./console/yii.php migrate-data/dataset-to-db 20220805_criteria.csv GeneService addCriteriaToGene**
