### ISSUE TITLE
Удалить неиспользуемые старые колонки в БД и поля в формах CMS

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#107]
1. Удалить колонку `commentCause` в таблице `gene`.
2. Удалить колонку `commentsReferenceLinks` в таблице  `gene` и поле в форме в CMS в **app/views/gene/_form.php** и упоминание поля в моделях
3. Удалить колонку `rating` в таблице  `gene`
4. Удалить колонку `why` в таблице  `gene` и поле в форме в CMS в **app/views/gene/_form.php**

**Comment by bavdalimbaev** [comment]
В миграционном контроллере есть метод **actionMigrateCommentCause** его цель заполнить таблицу **comment_cause** в других местах использование данной колонки не нашел.
миграции для удаления сделал, этот метод ** actionMigrateCommentCause** оставил не тронув

**Comment by bavdalimbaev** [comment]
Перед тем как выполнить миграцию, с начало проверьте пожалуйста 103 задачу.
