### ISSUE TITLE
Очистить таблицу gene_ontology, проверить почему возникают дубли, проверить парсинг

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#130]
# Задача

## Проблема
Проблема: много дублей GO terms, спаршенных из базы Gene Ontology в БД в таблице `gene_ontology`, а также механизмов старения в таблице `aging_mechanism`. 

## Пояснение
GO terms это аннотации генов из биологической базы Gene Ontology, они бывают трех типов: аннотации функции белка, связанных процессов и расположения продукта гена в клетке. GO term имеет свой собственный идентификатор (например `GO:0019221`) и описание.
В нашей БД им дополнительно задается свой id.

Проблема в том, что сейчас под разными id существует много дублей одних и тех же GO terms.
Например "GO:0019221" в таблице `gene_ontology` имеет дубли с id 13, 50, 87, 992.

Механизмы старения это наши собственные категории, которые задаются генам скриптом на основе набора соответствующих GO terms. Если появляются дубли GO terms, появляются и дубли механизмов старения. Неизвестно есть ли обратная зависимость.

<img width="1127" alt="scheme" src="https://user-images.githubusercontent.com/8498865/195673644-00a831b6-a66c-4997-b2e6-8545264d0754.png">

*Схема: структура колонок `gene_ontology` и `aging_mechanism` и связи между ними и `gene`.*

# Что нужно сделать

### Шаг 1

Написать скрипт для удаления всех записей в таблице gene_ontology, aging_mechanism и реляциях (см. схему). Нужно сделать это аккуратно.

### Шаг 2

Проверить создает ли скрипт  для парсинга GO terms дубли при выполнении. Этот скрипт запускается по графику в Cron.

```
# Парсинг GO terms из http://api.geneontology.org
php yii.php get-data/get-go-terms     [onlyNew default=true] true [geneNcbiIds default null] 1,2,3 [countRows default 2000] 2000
```

Получить GO terms для новых генов
```
php /var/www/open-genes/cms/app/console/yii.php  get-data/get-go-terms
```

Получить GO terms только для генов 114548 и 3600
```
php /var/www/open-genes/cms/app/console/yii.php get-data/get-go-terms false 114548,3600
```

### Шаг 3

- Проверить запуск крипта на поддомене test для тестовой БД. Если поставить парсинг для всех генов, скрипт будет выполняться долго, можно попробовать запустить его для какого-то небольшого количества генов.
- Запустить парсинг снова.
- После этого нужно проверить чтобы в БД не было дублей одних и тех же записей GO terms. 
- Также нужно проверить что отдает API:
  1. Сделать запрос https://test.open-genes.com/api/gene/*id гена* 
  2. Обратить внимание на объект `terms`. Сейчас там по 4-5 дублей каждого GO-terms.

### Шаг 4 

- Интеграционное тестирование. На поддомене test запустить скрипт из приложения API:

```
docker ps
```
Скопировать название контейнера для **opengenes/backend:test**

```
docker exec -it название_контейнера python3 scripts/aging_mechanisms/upload.py
```

[Подробнее о запуске скриптов в Docker](https://open-genes.notion.site/187945a22b2a4e6594fb9db9c74698ce)

- После этого проверить появились ли связи у таблицы `aging_mechanism` и `gene_ontology`

# Ожидаемый результат задачи (DoD):
В очищенную таблицу gene_ontology парсятся GO terms. При повторном запуске скрипта `get-go-terms` дубли не появляются. 
При запуске скрипта `aging_mechanisms/upload.py` появляются связи в таблицах с реляциями с `gene_ontology`. В таблице `gene_ontology` не появляются дубли.

**Comment by bavdalimbaev** [comment]
при билде на боевой, там есть одна миграция, она с начало удаляет все данные и связанные gene_ontology, затем создается ключ в gene_ontology для уникальности ontology_identifier

после того как билд завершится вы можете в бд проверить, и в бд должно быть уникальность и пустые таблицы gene_ontology, проверьте это пожалуйста.

если все верно, то запускаете полную 

php yii.php get-data/get-go-terms

если что то пошло не так сервер не завершил работу или ещё какие то неполадки то вы можете очистить данные и снова запустить скрипт,
для очистки данных вот это комманда

php yii.php drop-data/clear-ontology

далее проверьте заполнение таблиц по колличествам, затем запускаете скрипт который на python

и следом запускаете получение родителей go

php yii.php get-data/get-go-tree [onlyNew default=true]

php yii.php get-data/get-go-tree [onlyNew default=false]

затем заполнение механизмов

php yii.php get-data/update-go-to-aging-mechanisms
