### ISSUE TITLE
Унифицировать таблицу aging_mechanism и внешние ключи 

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#136]
Сделать в таблице aging_mechanism поле name_en уникальным.

Так же унифицировать внешние ключи таблиц многие ко многим.
gene_to_ontology
gene_ontology_to_aging_mechanism_visible
aging_mechanism_to_gene_ontology

**Comment by bavdalimbaev** [comment]
gene_ontology_to_aging_mechanism_visible уже были унифицированы внешними ключами
