### ISSUE TITLE
Скопировать данные из фиолетовых, зеленых и голубых форм одного гена в соответствующие формы другого гена для определенных организмов

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#80]
В БД скопировать данные экспериментов из фиолетовых (таблица `general_lifespan_experiment`), зеленых (таблица `gene_intervention_to_vital_process`) и голубых (таблица `age_related_change`) форм (см [типы исследований](https://purring-puma-ef9.notion.site/d886d16a693a490c94623491427cfeae?v=9e8c12920e1b4ccb929dea9109526201)) одного гена в соответствующие типы исследования другого гена.

Так как все в БД связано по реляции, то есть смежные таблицы с id генов и экспериментов.  Данные в колонке с id экспериментов для одних генов надо **дополнить** айдишниками экспериментов, указанных у других генов. 

Но нужно добавить id не всех экспериментов. Сначала нужно в посмотреть какой организм указан в эксперименте. Организм у всех исследований указан через id организма в колонке `model_organism_id`. Названия организмов находятся в таблице `model_organism`.

При добавлении id эксперимента, нужно убедиться, что у гена в колонке еще нет такого id эксперимента, чтобы не создавать лишних дублей.

 1. Из IGF1R в INSR, если организм круглый червь Caenorhabditis elegans и муха Drosophila melanogaster
 2. Из FOXO4 в FOXO1 и FOXO3, если организм муха Drosophila melanogaster
 3. Из FOXO3 в FOXO1 и FOXO4, если организм червь Caenorhabditis elegans
 4. Из PIK3CA в PIK3CB и PIK3CD, если организм червь Caenorhabditis elegans и муха Drosophila melanogaster
 5. Из HDAC1 в HDAC2, если организм муха Drosophila melanogaster
 6. Из GSK3A в GSK3B, если организм муха Drosophila melanogaster
 7. Из LMNB1 в LMNA, если организм муха Drosophila melanogaster
 8. Из LMNA в LMNB1, если организм червь Caenorhabditis elegans
 9. Из SNAI2 в SNAI1, если организм муха Drosophila melanogaster
 10. Из SMOC2 в SMOC1, если организм муха Drosophila melanogaster
 11. Из GDF11 в MSTN и TGFB1, если организм червь Caenorhabditis elegans
 12. Из GDF11 в MSTN, если организм муха Drosophila melanogaster
 13. Из AKT1 в AKT2 и AKT3, если организм червь Caenorhabditis elegans и муха Drosophila melanogaster
 14. Из MAPK8 в MAPK9 и MAPK10, если организм червь Caenorhabditis elegans и муха Drosophila melanogaster
 15. Из NOTCH3 в NOTCH1 и NOTCH2, если организм червь Caenorhabditis elegans
 16. Из JAK2 в JAK1, если организм муха Drosophila melanogaster
 17. Из IRS1 в IRS2, если организм муха Drosophila melanogaster
 18. Из INS в IGF1 и IGF2, если организм муха Drosophila melanogaster

**Comment by bavdalimbaev** [comment]
запуск командой.

php ./console/yii.php migrate-data/dataset-to-db copy-genes.csv GeneService copyDataToData

**Comment by const8ine** [comment]
1) В копировании исследований ошибка — там тот ген из которого копировали добавился как будто на него есть дополнительное воздействие в эксперименте. То есть как будто в одном эксперименте было два гена. Это моя вина, я не подумал что связь двух генов с одним id эксперимента приведет к такому.
Нужно подумать как сделать так, чтобы у другого гена был такой же эксперимент, но для него.

2) Не все пункты скопировались, например, в HDAC2 ничего не появилось

**Comment by const8ine** [comment]
Оказалось правильно копировать надо так:
Надо копироовать связь гена с `general_lifespan_experiment` вместе с привазанными к нему `lifespan_experiment`, а не `lifespan_experiment`
