### ISSUE TITLE
Добавить данные в БД из датасета по влиянию физической активности на экспрессию генов

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-cms#82]
Создать в БД новую таблицу с названием physical_activity по аналогии с уже существующей в БД таблицей diet. Даже названия многих колонок будут такими же. Такие поля как organism, line и т. д. должны хранить id соответствующих сущностей в БД, как и в diet.

[physical-activity.csv](https://github.com/open-genes/open-genes-cms/files/9072980/physical-activity.csv)

**Comment by bavdalimbaev** [comment]
в файле поле measurement_method имеет два значения 

microarray, qRT-PCR


microarray - существует в Базе а qRT-PCR в Базе нету, Что мне делать?

игнорировать второй и получить по первому id и добавлять?

так как я создал поле measurement_method_id int и связал с таблицей, невозможно добавить два id сразу, можно будет перебором два раза добавить.

Необходимо ваше направление.

**Comment by bavdalimbaev** [comment]
файл нужно добавить в папку /app/storage/dataset/*

**Comment by bavdalimbaev** [comment]
команда скрипта для запуска, выполняйте один раз проверка на дубликатов не предусмотрено

**Comment by const8ine** [comment]
Обновили датасет, добавились символы гена, там, где их не было. Убраны лишние колонки, которые и так не использовались скриптом, убраны данные по всем организмам, кроме человека. Скоро запушу.

[physical-activity.csv](https://github.com/open-genes/open-genes-cms/files/9135248/physical-activity.csv)

**Comment by bavdalimbaev** [comment]
Исправил данные в скрипте, попробуйте должно нормально отработать
